# Site
name: 'Soho Mandarin'
description: 'The latest in Chinese learning and Soho Mandarin related news.'
logo: 'assets/images/cslogotrans.png'
favicon: 'assets/images/sohosquaresotrans.png'
baseurl: ''
disqus: 'demowebsite'
email: 'michael@sohomandarin.com'

include: ["_pages"]
permalink: /think/:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    soho:
      name:           Soho Mandarin
      site:           https://www.sohomandarin.com
      avatar:         ../assets/images/sohosquarewhite.png
      bio:            "Soho Mandarin is an Chinese school taught online by native teachers living in China."
      email:          michael@sohomandarin.com
      url:            author-soho

    michaelliang:
      name:           Michael Liang
      site:           https://www.sohomandarin.com
      avatar:         ../assets/images/ml.jpg
      bio:            "Co-Founder of Soho Mandarin - online Chinese language school."
      email:          michael@sohomandarin.com
      url:            author-michael-liang

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: soho
      avatar: ../assets/images/sohosquarewhite.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]