# Site
name: 'Culturestride'
description: 'The latest in Chinese learning and Culturestride related news.'
logo: 'think/assets/images/cslogotrans.png'
favicon: 'think/assets/images/cslogotransbig.png'
baseurl: ''
disqus: 'demowebsite'
email: 'michael@culturestride.com'

include: ["_pages"]
permalink: /think/:title

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    culturestride:
      name:           Culturestride
      site:           https://culturestride.com
      avatar:         ../think/assets/images/cslogotrans.png
      bio:            "Culturestride is creating a more connected and emphathetic world through online language education."
      email:          michael@culturestride.com
      url:            /think/author-culturestride

    michaelliang:
      name:           Michael Liang
      site:           https://culturestride.com
      avatar:         ../think/assets/images/ml.jpg
      bio:            "Co-Founder of Culturestride."
      email:          michael@culturestride.com
      url:            /think/author-michael-liang

    kevinhuang:
      name:           Kevin Huang 
      site:           https://medium.com/kevins-dead
      avatar:         ../think/assets/images/kevin-huang.jpg
      bio:            "Culturestride Mandarin student since 2020"
      email:          https://medium.com/kevins-dead
      url:            /think/author-kevin-huang

    clintonchan:
      name:           Clinton Chan 
      site:           https://medium.com/kevins-dead
      avatar:         ../think/assets/images/amadeus.png
      bio:            "Guest Poster - Curious about all things tech, economics, philanthropy, and developmental political theory"
      email:          https://medium.com/kevins-dead
      url:            /think/author-clinton-chan

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: culturestride
      avatar: ../think/assets/images/cslogotrans.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 100



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]