# Site
name: 'Culturestride'
description: 'The latest in Chinese learning and Culturestride related news.'
logo: 'assets/images/cslogotrans.png'
favicon: 'assets/images/cslogotrans.png'
baseurl: 'culturestride.com'
disqus: 'demowebsite'
email: 'michael@culturestride.com'

include: ["_pages"]
permalink: /think/:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    culturestride:
      name:           Culturestride
      site:           https://www.culturestride.com
      avatar:         ../assets/images/cslogotrans.png
      bio:            "Culturestride is a platform creating global citizens."
      email:          michael@culturestride.com
      url:            author-culturestride

    michaelliang:
      name:           Michael Liang
      site:           https://www.culturestride.com
      avatar:         ../assets/images/ml.jpg
      bio:            "Co-Founder of Culturestride - creating global citizens."
      email:          michael@culturestride.com
      url:            author-michael-liang

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: culturestride
      avatar: ../assets/images/cslogotrans.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]